### ISSUE TITLE
Crash in Animator.addClass when the element is @containerless()

### ISSUE THREAD

**Issue by corneliutusnea** [aurelia/animator-css#38]
I have this piece of code
```
<workflow-report show.bind="model.options[0].enabled" config.bind="model"></workflow-report>
```
When this gets displayed I get the exception
```
ERROR [app-router] TypeError: Cannot read property 'add' of undefined
    at Animator.addClass (http://localhost:54804/app/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:83:24)
    at Show.valueChanged (http://localhost:54804/app/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.1/show.js:21:23)
    at Show.bind (http://localhost:54804/app/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.1/show.js:26:12)
    at Controller.bind (http://localhost:54804/app/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:2749:24)
    at View.bind (http://localhost:54804/app/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:843:24)
    at Controller.bind (http://localhost:54804/app/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:2747:19)
    at View.bind (http://localhost:54804/app/jspm_packages/npm/aurelia-templating@1.0.0-beta.1/aurelia-templating.js:843:24)
    at ArrayCollectionStrategy.processItems (http://localhost:54804/app/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.1/array-collection-strategy.js:30:14)
    at Repeat.processItemsByStrategy (http://localhost:54804/app/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.1/repeat.js:168:31)
    at Repeat._processItems (http://localhost:54804/app/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.1/repeat.js:129:14)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69processResult @ aurelia-router.js:1616(anonymous function) @ aurelia-router.js:1569run @ es6.promise.js:107(anonymous function) @ es6.promise.js:121flush @ $.microtask.js:25
aurelia-logging-console.js:62 ERROR [app-router] Router navigation failed, and no previous location could be restored.error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69restorePreviousLocation @ aurelia-router.js:1658processResult @ aurelia-router.js:1619(anonymous function) @ aurelia-router.js:1569run @ es6.promise.js:107(anonymous function) @ es6.promise.js:121flush @ $.microtask.js:25
```

This seems to happen when the workflow-report is marked as `@containerless()`

**Comment by EisenbergEffect** [comment]
Yes, you are getting that error because there is literally no `workflow-report` to show/hide. The container element doesn't exist. I recommend not using containerless elements in general. It's an edge case thing, mostly meant to be used with router-view and compose. You shouldn't build standard custom elements in this way.
